
version: '4.0'

actions:

  generate_numeric_value_dataset:
    run: >
      ehrql:v1 generate-dataset
        analysis/numeric_value_dataset_definition.py
        --output output/numeric_value_dataset.csv
        --
        --codelist codelists/opensafely-alanine-aminotransferase-alt-tests.csv
    outputs:
      highly_sensitive:
        dataset: output/numeric_value_dataset.csv
  generate_numeric_value_histogram:
    run: >
      r:latest analysis/histogram.r --codelist codelists/opensafely-alanine-aminotransferase-alt-tests.csv
    needs: [generate_numeric_value_dataset]
    outputs:
      moderately_sensitive:
        pic: output/alt_numeric_values.png
        pic2: output/alt_numeric_values_zoomed.png
        dataset: output/top_1000_numeric_values.csv

  generate_measures_alt_has_test_value:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/measures_alt_has_test_value.csv
        --
        --codelist codelists/opensafely-alanine-aminotransferase-alt-tests.csv
        --measure has_test_value
    outputs:
      moderately_sensitive:
        measures: output/measures_alt_has_test_value.csv

  generate_measures_alt_has_equality_comparator:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/measures_alt_has_equality_comparator.csv
        --
        --codelist codelists/opensafely-alanine-aminotransferase-alt-tests.csv
        --measure has_equality_comparator
    outputs:
      moderately_sensitive:
        measures: output/measures_alt_has_equality_comparator.csv

  generate_measures_alt_has_differential_comparator:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/measures_alt_has_differential_comparator.csv
        --
        --codelist codelists/opensafely-alanine-aminotransferase-alt-tests.csv
        --measure has_differential_comparator
    outputs:
      moderately_sensitive:
        measures: output/measures_alt_has_differential_comparator.csv

  generate_measures_alt_has_lower_bound:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/measures_alt_has_lower_bound.csv
        --
        --codelist codelists/opensafely-alanine-aminotransferase-alt-tests.csv
        --measure has_lower_bound
    outputs:
      moderately_sensitive:
        measures: output/measures_alt_has_lower_bound.csv

  generate_measures_alt_has_upper_bound:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/measures_alt_has_upper_bound.csv
        --
        --codelist codelists/opensafely-alanine-aminotransferase-alt-tests.csv
        --measure has_upper_bound
    outputs:
      moderately_sensitive:
        measures: output/measures_alt_has_upper_bound.csv

  generate_measures_chol_has_test_value:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/measures_chol_has_test_value.csv
        --
        --codelist codelists/opensafely-cholesterol-tests.csv
        --measure has_test_value
    outputs:
      moderately_sensitive:
        measures: output/measures_chol_has_test_value.csv

  generate_measures_chol_has_equality_comparator:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/measures_chol_has_equality_comparator.csv
        --
        --codelist codelists/opensafely-cholesterol-tests.csv
        --measure has_equality_comparator
    outputs:
      moderately_sensitive:
        measures: output/measures_chol_has_equality_comparator.csv

  generate_measures_chol_has_differential_comparator:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/measures_chol_has_differential_comparator.csv
        --
        --codelist codelists/opensafely-cholesterol-tests.csv
        --measure has_differential_comparator
    outputs:
      moderately_sensitive:
        measures: output/measures_chol_has_differential_comparator.csv

  generate_measures_chol_has_lower_bound:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/measures_chol_has_lower_bound.csv
        --
        --codelist codelists/opensafely-cholesterol-tests.csv
        --measure has_lower_bound
    outputs:
      moderately_sensitive:
        measures: output/measures_chol_has_lower_bound.csv

  generate_measures_chol_has_upper_bound:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/measures_chol_has_upper_bound.csv
        --
        --codelist codelists/opensafely-cholesterol-tests.csv
        --measure has_upper_bound
    outputs:
      moderately_sensitive:
        measures: output/measures_chol_has_upper_bound.csv

  generate_measures_hba1c_has_test_value:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/measures_hba1c_has_test_value.csv
        --
        --codelist codelists/opensafely-glycated-haemoglobin-hba1c-tests.csv
        --measure has_test_value
    outputs:
      moderately_sensitive:
        measures: output/measures_hba1c_has_test_value.csv

  generate_measures_hba1c_has_equality_comparator:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/measures_hba1c_has_equality_comparator.csv
        --
        --codelist codelists/opensafely-glycated-haemoglobin-hba1c-tests.csv
        --measure has_equality_comparator
    outputs:
      moderately_sensitive:
        measures: output/measures_hba1c_has_equality_comparator.csv

  generate_measures_hba1c_has_differential_comparator:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/measures_hba1c_has_differential_comparator.csv
        --
        --codelist codelists/opensafely-glycated-haemoglobin-hba1c-tests.csv
        --measure has_differential_comparator
    outputs:
      moderately_sensitive:
        measures: output/measures_hba1c_has_differential_comparator.csv

  generate_measures_hba1c_has_lower_bound:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/measures_hba1c_has_lower_bound.csv
        --
        --codelist codelists/opensafely-glycated-haemoglobin-hba1c-tests.csv
        --measure has_lower_bound
    outputs:
      moderately_sensitive:
        measures: output/measures_hba1c_has_lower_bound.csv

  generate_measures_hba1c_has_upper_bound:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/measures_hba1c_has_upper_bound.csv
        --
        --codelist codelists/opensafely-glycated-haemoglobin-hba1c-tests.csv
        --measure has_upper_bound
    outputs:
      moderately_sensitive:
        measures: output/measures_hba1c_has_upper_bound.csv

  generate_measures_rbc_has_test_value:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/measures_rbc_has_test_value.csv
        --
        --codelist codelists/opensafely-red-blood-cell-rbc-tests.csv
        --measure has_test_value
    outputs:
      moderately_sensitive:
        measures: output/measures_rbc_has_test_value.csv

  generate_measures_rbc_has_equality_comparator:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/measures_rbc_has_equality_comparator.csv
        --
        --codelist codelists/opensafely-red-blood-cell-rbc-tests.csv
        --measure has_equality_comparator
    outputs:
      moderately_sensitive:
        measures: output/measures_rbc_has_equality_comparator.csv

  generate_measures_rbc_has_differential_comparator:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/measures_rbc_has_differential_comparator.csv
        --
        --codelist codelists/opensafely-red-blood-cell-rbc-tests.csv
        --measure has_differential_comparator
    outputs:
      moderately_sensitive:
        measures: output/measures_rbc_has_differential_comparator.csv

  generate_measures_rbc_has_lower_bound:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/measures_rbc_has_lower_bound.csv
        --
        --codelist codelists/opensafely-red-blood-cell-rbc-tests.csv
        --measure has_lower_bound
    outputs:
      moderately_sensitive:
        measures: output/measures_rbc_has_lower_bound.csv

  generate_measures_rbc_has_upper_bound:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/measures_rbc_has_upper_bound.csv
        --
        --codelist codelists/opensafely-red-blood-cell-rbc-tests.csv
        --measure has_upper_bound
    outputs:
      moderately_sensitive:
        measures: output/measures_rbc_has_upper_bound.csv

  generate_measures_sodium_has_test_value:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/measures_sodium_has_test_value.csv
        --
        --codelist codelists/opensafely-sodium-tests-numerical-value.csv
        --measure has_test_value
    outputs:
      moderately_sensitive:
        measures: output/measures_sodium_has_test_value.csv

  generate_measures_sodium_has_equality_comparator:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/measures_sodium_has_equality_comparator.csv
        --
        --codelist codelists/opensafely-sodium-tests-numerical-value.csv
        --measure has_equality_comparator
    outputs:
      moderately_sensitive:
        measures: output/measures_sodium_has_equality_comparator.csv

  generate_measures_sodium_has_differential_comparator:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/measures_sodium_has_differential_comparator.csv
        --
        --codelist codelists/opensafely-sodium-tests-numerical-value.csv
        --measure has_differential_comparator
    outputs:
      moderately_sensitive:
        measures: output/measures_sodium_has_differential_comparator.csv

  generate_measures_sodium_has_lower_bound:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/measures_sodium_has_lower_bound.csv
        --
        --codelist codelists/opensafely-sodium-tests-numerical-value.csv
        --measure has_lower_bound
    outputs:
      moderately_sensitive:
        measures: output/measures_sodium_has_lower_bound.csv

  generate_measures_sodium_has_upper_bound:
    run: >
      ehrql:v1 generate-measures
        analysis/measure_definition.py
        --output output/measures_sodium_has_upper_bound.csv
        --
        --codelist codelists/opensafely-sodium-tests-numerical-value.csv
        --measure has_upper_bound
    outputs:
      moderately_sensitive:
        measures: output/measures_sodium_has_upper_bound.csv

  # Runs test to ensure correctness of measures queries
  generate_test_dataset:
    run: >
      ehrql:v1 generate-dataset
        analysis/dataset_definition.py
        --output output/test_dataset.csv
        --test-data-file analysis/test_dataset_definition.py
        --
        --codelist codelists/opensafely-alanine-aminotransferase-alt-tests.csv
    outputs:
      highly_sensitive:
        dataset: output/test_dataset.csv
