name: Test that the project is runnable

on: [push, workflow_dispatch]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DOCKER_RO_TOKEN: ${{ secrets.DOCKER_RO_TOKEN }}
  STATA_LICENSE: ${{ secrets.STATA_LICENSE }}
  HONEYCOMB_API_KEY: ${{ secrets.HONEYCOMB_API_KEY }}
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test the project can run, using dummy data
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Test that the project is runnable
      uses: opensafely-core/research-action@v2
      with:
        actions: generate_measures_alt_has_zero_value generate_measures_chol_has_zero_value generate_measures_sodium_has_zero_value generate_measures_rbc_has_zero_value generate_measures_hba1c_has_zero_value generate_measures_hba1c_numeric_has_zero_value
